# Generated by Django 2.2.1 on 2019-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BraTS_3D_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mricase',
            name='case_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
